name: Sync from Repo A

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo B
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync from Repo A
        uses: repo-sync/github-sync@v2.3.0
        with:
          source_repo: https://github.com/work-alaskarian/FinanceSystem.git
          source_branch: main
          destination_branch: main
          github_token: ${{ github.token }}
          sync_tags: true
